[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/riscv32imc-unknown-none-elf/debug/esp32-robot-management-unit"
firmware = "target/riscv32imc-unknown-none-elf/debug/esp32-robot-management-unit"
